### ISSUE TITLE
POESP_board - resistors R20, R27 value

### ISSUE THREAD

**Issue by ghost** [MakerSpaceLeiden/AccesSystem#26]
Hi
I read schematic [board](https://github.com/MakerSpaceLeiden/AccesSystem/blob/master/POESP_board/poesp_1.0.sch) and I don't know value for resistors R20 and R27. 
In schematic is written R20=bead and R27=np. 
Is it shortcut for something?
Can you write real values of this resistors?
Thank you

**Comment by dirkx** [comment]
You’d have to contact Aart to get the right answer; but NP means not-placed. And looking at the board - R20 is just a standard/cheap ferrite bead - the last one I repaired used Würth 74279266 or 742792651 (not sure).

**Comment by dirkx** [comment]
You probably want to look at revision v1.12 or newer of this: https://oshwlab.com/dirkx/msl-node-4g-107 board now.
